In [1]:
import numpy as np
import os
import pandas as pd
import random
import matplotlib.pyplot as plt

In [2]:
def resize_dat(x, img_size, img_width, img_height, input_size):
    cell_size = int(img_size//input_size)
    
    enlarged_dat = []
    for j in range(x.shape[0]):
        dat = x[j]
        tmp = []
        for i in range(dat.shape[0]):
            for _ in range(cell_size):
                tmp.append(dat[i])
        tmp = np.array(tmp).reshape([img_height, img_width])
        enlarged_dat.append(tmp)
    enlarged_dat = np.array(enlarged_dat)    
    return enlarged_dat

In [6]:
data_alt3_pd = pd.read_csv('data/netflix_data_3alt.csv')
data_alt3_pd = data_alt3_pd.iloc[:,1:]
# print(data_alt3.head())
data_alt3 = data_alt3_pd.iloc[:,1:].values
print(data_alt3[:5])

[[125 324   1   0   1   0]
 [ 56  11 120  88  41 128]
 [196  85   4   0   2   0]
 [ 45   3 271  49   6  23]
 [101  30  40  17  79  35]]


In [4]:
data_alt3_pd.columns

Index(['movies', 'ABC', 'ACB', 'BAC', 'BCA', 'CAB', 'CBA'], dtype='object')

# normalization


In [9]:
sum_vote = np.sum(data_alt3, 1)
print(sum_vote.shape)
data_alt3_normal = np.divide(data_alt3.T, sum_vote).T
print(data_alt3_normal.shape)

(4860,)
(4860, 6)


# resize

In [10]:
img_size = np.math.factorial(6)
img_width = 30
# img_width = 24
img_height = 24
input_size = np.math.factorial(3)

election_data_alt3_resize = resize_dat(data_alt3_normal, img_size, img_width, img_height, input_size)


print(election_data_alt3_resize.shape)

ValueError: cannot reshape array of size 720 into shape (24,24)

In [ ]:
fig, ax = plt.subplots(figsize=(5, 5))
ax.cla()
ax.imshow(np.reshape(election_data_alt3_resize[2], (img_height, img_width)), cmap='gray')

In [ ]:
election_data_alt3_resize = election_data_alt3_resize.reshape([-1, img_height * img_width])
print(election_data_alt3_resize.shape)

In [ ]:
election_data_alt3_resize = pd.DataFrame(election_data_alt3_resize)
election_data_alt3_resize.to_csv('./data/netflix_data_3alt_square.csv')

# -------------------------------------------------------------------------

In [ ]:
data_alt4_pd = pd.read_csv('data/netflix_data_4alt.csv')
data_alt4_pd = data_alt4_pd.iloc[:,1:]
# data_alt4.head()
data_alt4 = data_alt4_pd.iloc[:,1:].values

In [ ]:
data_alt4_pd.columns

# normalization

In [ ]:
sum_vote = np.sum(data_alt4, 1)
print(sum_vote.shape)
data_alt4_normal = np.divide(data_alt4.T, sum_vote).T
print(data_alt4_normal.shape)

In [ ]:
data_alt4_normal[0]

# resize

In [ ]:
img_size = np.math.factorial(6)
# img_width = 30
img_width = 24
img_height = 24
input_size = np.math.factorial(4)

election_data_alt4_resize = resize_dat(data_alt4_normal, img_size, img_width, img_height, input_size)
print(election_data_alt4_resize.shape)

In [ ]:
fig, ax = plt.subplots(figsize=(5, 5))
ax.cla()
ax.imshow(np.reshape(election_data_alt4_resize[99], (img_height, img_width)), cmap='gray')

In [ ]:
election_data_alt4_resize = election_data_alt4_resize.reshape([-1, img_height * img_width])
print(election_data_alt4_resize.shape)

In [ ]:
election_data_alt4_resize = pd.DataFrame(election_data_alt4_resize)
election_data_alt4_resize.to_csv('./data/netflix_data_4alt_square.csv')